version: '3'

services:
  database:
    image: mysql:8.0.31
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci -h0.0.0.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: progjog_db
      MYSQL_USER: progjog_user
    ports:
      - "3306:3306"

